### ISSUE TITLE
Dependencies are out of date and insecure!

### ISSUE THREAD

**Issue by tooomm** [thomasbrueggemann/paperless-desktop#46]
As realized in https://github.com/danielquinn/paperless/issues/389#issuecomment-415796299, the dependencies you use for your project contain security vulnerabilities as can be seen here:
https://david-dm.org/thomasbrueggemann/paperless-desktop

I happily open a PR and add tracking badges to your readme:
[![Dependencies](https://david-dm.org/thomasbrueggemann/paperless-desktop.svg)](https://david-dm.org/thomasbrueggemann/paperless-desktop) [![Dev Dependencies](https://david-dm.org/thomasbrueggemann/paperless-desktop/dev-status.svg)](https://david-dm.org/thomasbrueggemann/paperless-desktop?type=dev)

**Comment by thomasbrueggemann** [comment]
Thanks for taking a look into this, @tooomm 
The outdated dependencies are unpleasant, but could only be resolved by investing quite some time in updating them and implementing the API changes of the newer dependency versions. Time that I sadly cannot invest at the moment. But you are very welcome to contribute to updating the dependencies and testing the app afterwards.

If you look closely at the `slug` and `moment` security warnings: The threats are "Regular Expression Denial of Service". So if large or malicous userinput is directly passed to `slug` of `moment` functions, it could cause the process to lag or terminate. This is a threat if the exeuting process is a webserver for example. Since paperless-desktop is a desktop application running - most likely - on your own computer, it makes little to no sense to DoS your own computer and slow down your own work :-) 

But as I said: it would be awesome to have all green lights on these depenency pages. But I would refrain from putting up these badges, given the explanation above.
